In [2]:
#1
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()
A = np.random.randint(0, 20, size=(5, 5))
print('\nMatrix A：')
print(A)
# Создать случайный набор цитат
A_index = np.random.permutation(5)
# Перегруппировка столбцов А по индексу столбцов
B = A[:, A_index]

print('-----------------------------------------------------------','\nЗадача 1：')
print(B)




Matrix A：
[[19  0  6 14  6]
 [ 6  2  7 15 10]
 [15 12  0 15  9]
 [17  2 10 14 10]
 [ 5 14 13 18 14]]
----------------------------------------------------------- 
Задача 1：
[[ 6  0 14 19  6]
 [10  2 15  6  7]
 [ 9 12 15 15  0]
 [10  2 14 17 10]
 [14 14 18  5 13]]


In [3]:
#2
# Расчет суммы четных и нечетных столбцов
even_sum = np.sum(A[:, ::2], axis=1)
odd_sum = np.sum(A[:, 1::2], axis=1)
# Вычислить среднее нечетное число
odd_avg = np.mean(odd_sum)
# Вернуться к строке выполнения условий
B=A[even_sum > odd_avg]

print('-----------------------------------------------------------','\nЗадача 2：')
print(B)



----------------------------------------------------------- 
Задача 2：
[[19  0  6 14  6]
 [ 6  2  7 15 10]
 [15 12  0 15  9]
 [17  2 10 14 10]
 [ 5 14 13 18 14]]


In [4]:
#3
# Вычислить максимальные и минимальные значения для каждой строки            
max_values = np.max(A, axis=1)
min_values = np.min(A, axis=1)
# Расчет разницы между максимальным и минимальным значениями       
diff = max_values - min_values
result=np.where(diff==np.max(diff,axis=0))
# Вернуться к индексу строк с наибольшей разницей
print('-----------------------------------------------------------','\nЗадача 3：')
print('Разница между наибольшим и наименьшим элементами массива А：'+str(result[0][0]))



----------------------------------------------------------- 
Задача 3：
Разница между наибольшим и наименьшим элементами массива А：0


In [5]:
#4
# Получение индексов после сортировки
temp = A.argsort()
# Пересортировка для получения рейтинга
rank = temp.argsort() + 1
print('-----------------------------------------------------------','\nЗадача 4：')
print('Генерирует массивы с тем же измерением, что и A, но каждый элемент заменяется серийным номером в массиве с повышенным порядком A (начиная с 1)：')
print(rank)



----------------------------------------------------------- 
Задача 4：
Генерирует массивы с тем же измерением, что и A, но каждый элемент заменяется серийным номером в массиве с повышенным порядком A (начиная с 1)：
[[5 1 2 4 3]
 [2 1 3 5 4]
 [4 3 1 5 2]
 [5 1 2 4 3]
 [1 3 2 5 4]]


In [6]:
#5
# Расчет минимального и максимального значений для каждой строки
mins =np.min(A,axis=1)
maxs = np.max(A,axis=1)
# Стандартизация min - max для каждой строки
nor_A = (A - mins) / (maxs - mins)
print('-----------------------------------------------------------','\nЗадача 5：')
print(np.round(nor_A,2))



----------------------------------------------------------- 
Задача 5：
[[ 1.   -0.15  0.4   0.8   0.08]
 [ 0.32  0.    0.47  0.87  0.38]
 [ 0.79  0.77  0.    0.87  0.31]
 [ 0.89  0.    0.67  0.8   0.38]
 [ 0.26  0.92  0.87  1.07  0.69]]


In [7]:
#6
# Определение элемента А
a = np.arange(1, 11)
# Создать новый трехмерный массив
A2 =np.arange(100000).reshape((10, 200, 50))
# Использовать цикл для создания подмножества
for i in range(10):
    A2[i, :, 0] = A2[i, :, 0]*a[i]

print('-----------------------------------------------------------','\nЗадача 6：')
print(A2)



----------------------------------------------------------- 
Задача 6：
[[[     0      1      2 ...     47     48     49]
  [    50     51     52 ...     97     98     99]
  [   100    101    102 ...    147    148    149]
  ...
  [  9850   9851   9852 ...   9897   9898   9899]
  [  9900   9901   9902 ...   9947   9948   9949]
  [  9950   9951   9952 ...   9997   9998   9999]]

 [[ 20000  10001  10002 ...  10047  10048  10049]
  [ 20100  10051  10052 ...  10097  10098  10099]
  [ 20200  10101  10102 ...  10147  10148  10149]
  ...
  [ 39700  19851  19852 ...  19897  19898  19899]
  [ 39800  19901  19902 ...  19947  19948  19949]
  [ 39900  19951  19952 ...  19997  19998  19999]]

 [[ 60000  20001  20002 ...  20047  20048  20049]
  [ 60150  20051  20052 ...  20097  20098  20099]
  [ 60300  20101  20102 ...  20147  20148  20149]
  ...
  [ 89550  29851  29852 ...  29897  29898  29899]
  [ 89700  29901  29902 ...  29947  29948  29949]
  [ 89850  29951  29952 ...  29997  29998  29999]]

 ...


In [8]:
#7
#Получите ровные колонки
B = A2[:, ::2]
# Получение нечетных столбцов
C = A2[:, 1::2]
# Комбинирование четных и нечетных столбцов
D = np.concatenate([B, C], axis=1)

print('-----------------------------------------------------------','\nЗадача 7：')
print(D)



----------------------------------------------------------- 
Задача 7：
[[[     0      1      2 ...     47     48     49]
  [   100    101    102 ...    147    148    149]
  [   200    201    202 ...    247    248    249]
  ...
  [  9750   9751   9752 ...   9797   9798   9799]
  [  9850   9851   9852 ...   9897   9898   9899]
  [  9950   9951   9952 ...   9997   9998   9999]]

 [[ 20000  10001  10002 ...  10047  10048  10049]
  [ 20200  10101  10102 ...  10147  10148  10149]
  [ 20400  10201  10202 ...  10247  10248  10249]
  ...
  [ 39500  19751  19752 ...  19797  19798  19799]
  [ 39700  19851  19852 ...  19897  19898  19899]
  [ 39900  19951  19952 ...  19997  19998  19999]]

 [[ 60000  20001  20002 ...  20047  20048  20049]
  [ 60300  20101  20102 ...  20147  20148  20149]
  [ 60600  20201  20202 ...  20247  20248  20249]
  ...
  [ 89250  29751  29752 ...  29797  29798  29799]
  [ 89550  29851  29852 ...  29897  29898  29899]
  [ 89850  29951  29952 ...  29997  29998  29999]]

 ...


In [9]:
#8
A = np.random.randint(0, 20, size=(5, 5))
#Используйте np.all(), чтобы получить одномерный булев массив
A_than_5 = np.all(A>5, axis=1)

# Подсчитайте количество строк, в которых все элементы больше 5
nums = np.sum(A_than_5)

print('-----------------------------------------------------------','\nЗадача 8：')
print(f"Количество строк в массиве A, в которых все элементы больше 5, равно：{nums}")

----------------------------------------------------------- 
Задача 8：
Количество строк в массиве A, в которых все элементы больше 5, равно：0


Задание 2.9 (2 балла)
Поделите массив A горизонтально на 10 частей и создайте новый массив размерности , который является средним этих частей. Используйте np.split()